// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GaraMS.Data.Models;

public partial class Appointment
{
    [Key]
    public int AppointmentId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    public string Note { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdatedAt { get; set; }

    public int? WaitingTime { get; set; }

    public string RejectReason { get; set; }

    public int? VehicleId { get; set; }

    public int? AppointmentStatusId { get; set; }

    [InverseProperty("Appointment")]
    public virtual ICollection<AppointmentService> AppointmentServices { get; set; } = new List<AppointmentService>();

    [ForeignKey("AppointmentStatusId")]
    [InverseProperty("Appointments")]
    public virtual AppointmentStatus AppointmentStatus { get; set; }

    [InverseProperty("Appointment")]
    public virtual Invoice Invoice { get; set; }

    [ForeignKey("VehicleId")]
    [InverseProperty("Appointments")]
    public virtual Vehicle Vehicle { get; set; }
}