// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GaraMS.Data.Models;

[Table("EmployeeShift")]
public partial class EmployeeShift
{
    [Key]
    public int EmployeeShiftId { get; set; }

    public int? EmployeeId { get; set; }

    public int? ShiftId { get; set; }

    public int Month { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeShifts")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("ShiftId")]
    [InverseProperty("EmployeeShifts")]
    public virtual Shift Shift { get; set; }
}