// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class Gara
{
    public int GaraId { get; set; }

    public string GaraNumber { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }
}