// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class InventorySupplier
{
    public int InventorySupplierId { get; set; }

    public int? InventoryId { get; set; }

    public int? SupplierId { get; set; }

    public virtual Inventory Inventory { get; set; }

    public virtual Supplier Supplier { get; set; }
}