// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GaraMS.Data.Models;

[Table("InventoryInvoice")]
public partial class InventoryInvoice
{
    [Key]
    public int InventoryInvoiceId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    [StringLength(100)]
    public string DiliverType { get; set; }

    [StringLength(100)]
    public string PaymentMethod { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalAmount { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Date { get; set; }

    public int? UserId { get; set; }

    [InverseProperty("InventoryInvoice")]
    public virtual ICollection<InventoryInvoiceDetail> InventoryInvoiceDetails { get; set; } = new List<InventoryInvoiceDetail>();

    [ForeignKey("UserId")]
    [InverseProperty("InventoryInvoices")]
    public virtual User User { get; set; }
}