// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GaraMS.Data.Models;

[Table("InventoryInvoiceDetail")]
public partial class InventoryInvoiceDetail
{
    [Key]
    public int InventoryInvoiceDetailId { get; set; }

    public int? InventoryId { get; set; }

    public int? InventoryInvoiceId { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? Price { get; set; }

    [ForeignKey("InventoryId")]
    [InverseProperty("InventoryInvoiceDetails")]
    public virtual Inventory Inventory { get; set; }

    [ForeignKey("InventoryInvoiceId")]
    [InverseProperty("InventoryInvoiceDetails")]
    public virtual InventoryInvoice InventoryInvoice { get; set; }

    [InverseProperty("InventoryInvoiceDetail")]
    public virtual ICollection<InventoryWarranty> InventoryWarranties { get; set; } = new List<InventoryWarranty>();
}