// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GaraMS.Data.Models;

[Table("InventoryWarranty")]
public partial class InventoryWarranty
{
    [Key]
    public int InventoryWarrantyId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime StartDay { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EndDay { get; set; }

    public bool? Status { get; set; }

    public int? InventoryInvoiceDetailId { get; set; }

    public int? AppointmentId { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("InventoryWarranties")]
    public virtual Appointment Appointment { get; set; }

    [ForeignKey("InventoryInvoiceDetailId")]
    [InverseProperty("InventoryWarranties")]
    public virtual InventoryInvoiceDetail InventoryInvoiceDetail { get; set; }
}