// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class InvoiceDetail
{
    public int InvoiceDetailId { get; set; }

    public decimal? Price { get; set; }

    public int? InvoiceId { get; set; }

    public virtual Invoice Invoice { get; set; }
}