// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class Manager
{
    public int ManagerId { get; set; }

    public string Gender { get; set; }

    public decimal? Salary { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }
}