// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class Promotion
{
    public int PromotionId { get; set; }

    public string PromotionName { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public decimal? DiscountPercent { get; set; }

    public virtual ICollection<ServicePromotion> ServicePromotions { get; set; } = new List<ServicePromotion>();
}