// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class ServiceEmployee
{
    public int ServiceEmployeeId { get; set; }

    public int? ServiceId { get; set; }

    public int? EmployeeId { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual Service Service { get; set; }
}