// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class ServicePromotion
{
    public int ServicePromotionId { get; set; }

    public int? ServiceId { get; set; }

    public int? PromotionId { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual Service Service { get; set; }
}