// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GaraMS.Data.Models;

public partial class Specialized
{
    public int SpecializedId { get; set; }

    public string SpecializedName { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}